version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: raffle_system
      POSTGRES_PASSWORD: raffle_system
      POSTGRES_DB: raffle_system_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://raffle_system:raffle_system@postgres:5432/raffle_system_db
      - REDIS_HOST=redis
    ports:
      - "4000:3000"
    depends_on:
      - postgres
      - redis

  admin:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - api

  client-landing:
    build:
      context: ./apps/client-landing
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3000"
    depends_on:
      - api

volumes:
  postgres-data:
