version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: raffle_system
      POSTGRES_PASSWORD: raffle_system
      POSTGRES_DB: raffle_system_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgresql://raffle_system:raffle_system@postgres:5432/raffle_system_db
      REDIS_HOST: redis
    ports:
      - "4000:3000"
    depends_on:
      - postgres
      - redis

  admin:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
    volumes:
      - ./apps/admin:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api

  client-landing:
    build:
      context: ./apps/client-landing
      dockerfile: Dockerfile
    volumes:
      - ./apps/client-landing:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - api

volumes:
  postgres-data:
